
/*****************************************************************************
 * This will hold the code for the Iventory of shows and associated details
 * 
 * @author (Anyanwu Benedict Chukwuemeka)
 * @version (v0.01)
 *
*****************************************************************************/

    const searchInventory =
    [
        // Anime content
        {
            show_link: `/Library/Anime/JujutsuKaisen.html`,
            show_thumbnail: `/Library/Anime/img/1.jpg`,
            show_title: `Jujutsu Kaisen`,
            show_type: `TV`,
            show_status: `Finished Airing`,
            show_languages: `Japanese`,
            show_subtitles: `Japanese`,
            show_genre: ``,
            show_theme: `school, sorcery, magical, battles`,
            show_year: `2018`,
            show_aired: `Oct 03, 2020 to Dec 28, 2023`,
            show_studios: `MAPPA`,
            show_country: `Japan`,
            show_foreground: `/Library/Anime/Watch/JujutsuKaisen/img/1.jpg`,
            show_background: `/Library/Anime/Watch/JujutsuKaisen/img/2.jpg`,
            show_quality: `HD`,
            show_rating: `PG 13`,
            show_scores: `9.2`,
            show_trailers: [{show_trl: `https://www.youtube.com/embed/4A_X-Dvl0ws`}],
            show_movies: [{show_mov: `JJK0`}],
            show_episodes: [{show_ep: 24,}, {show_ep: 23,}],
            show_watch: [{show_wtp: `tv`, show_wep: 24,}, {show_wtp: `movie`, show_wep: `JJK0`,}, {show_wtp: `tv`, show_wep: 23,}, {show_wtp: `movie`, show_wep: `JJK1`,},],
            show_description: `Jujutsu Kaisen is a popular anime series that premiered in 2018. 
            It is based on the manga of the same name written and illustrated by Gege Akutami. 
            The story follows a high school student named Yuji Itadori who becomes a Jujutsu Sorcerer
            after swallowing a cursed object to protect his friends.
            He then joins the Tokyo Metropolitan Magic Technical College to learn more about Jujutsu and fight against cursed spirits.`,
            show_searchKey: `Jujutsu Kaisen sorcery anime`,
        },
        {
            show_link: `/Library/Anime/DemonSlayer.html`,
            show_thumbnail: `/Library/Anime/img/2.jpg`,
            show_title: `Demon Slayer`,
            show_type: `TV`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Demon Slayer Kimetsu No Yaiba anime`,
        },
        {
            show_link: `/Library/Anime/AttackOnTitan.html`,
            show_thumbnail: `/Library/Anime/img/3.jpg`,
            show_title: `Attack On Titan`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Shingeki no Kyojin Attack On Titan anime`,
        },
        {
            show_link: `/Library/Anime/Naruto.html`,
            show_thumbnail: `/Library/Anime/img/4.jpg`,
            show_title: `Naruto`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Naruto anime`,
        },
        {
            show_link: `/Library/Anime/FullmetalPanic.html`,
            show_thumbnail: `/Library/Anime/img/5.jpg`,
            show_title: `Fullmetal Panic`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Furumetaru Panikku Fullmetal Panic anime`,
        },
        {
            show_link: `/Library/Anime/FullmetalAlchemist.html`,
            show_thumbnail: `/Library/Anime/img/6.jpg`,
            show_title: `Fullmetal Alchemist`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Hagane no Renkinjutsushi Fullmetal Alchemist anime`,
        },
        {
            show_link: `/Library/Anime/FullmetalAlchemistBrotherhood.html`,
            show_thumbnail: `/Library/Anime/img/7.jpg`,
            show_title: `Fullmetal Alchemist Brotherhood`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Hagane no Renkinjutsushi Fullmetal Alchemist Brotherhood anime`,
        },
        {
            show_link: `/Library/Anime/ClassroomoftheElite.html`,
            show_thumbnail: `/Library/Anime/img/8.jpg`,
            show_title: `Classroom of the Elite`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Classroom of the Elite Yokoso Jitsuryoku Shijo Shugi no Kyoshitsu anime`,
        },
        {
            show_link: `/Library/Anime/BlueExorcist.html`,
            show_thumbnail: `/Library/Anime/img/9.jpg`,
            show_title: `Blue Exorcist`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Ao no Ekusoshisuto Gekijoban Blue Exorcist anime`,
        },
        {
            show_link: `/Library/Anime/RentaGirlfriend.html`,
            show_thumbnail: `/Library/Anime/img/10.jpg`,
            show_title: `Spy X Family`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Spy X Family anime`,
        },
        {
            show_link: `/Library/Anime/Naruto.html`,
            show_thumbnail: `/Library/Anime/img/11.jpg`,
            show_title: `Rent a Girlfriend`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Rent a Girlfriend Kanojo Okarishimasu anime`,
        },
        {
            show_link: `/Library/Anime/TokyoGhoul.html`,
            show_thumbnail: `/Library/Anime/img/12.jpg`,
            show_title: `Tokyo Ghoul`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Tokyo Ghoul Tokyo Guru anime`,
        },
        {
            show_link: `/Library/Anime/InazumaEleven.html`,
            show_thumbnail: `/Library/Anime/img/13.jpg`,
            show_title: `Inazuma Eleven`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Inazuma Eleven Inazuma Irebun anime`,
        },
        {
            show_link: `/Library/Anime/Aoashi.html`,
            show_thumbnail: `/Library/Anime/img/14.jpg`,
            show_title: `Aoashi`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Aoashi anime`,
        },
        {
            show_link: `/Library/Anime/CyberpunkEdgeRunners.html`,
            show_thumbnail: `/Library/Anime/img/15.jpg`,
            show_title: `Cyberpunk: EdgeRunners`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Cyberpunk Edgerunners Saibapanku Edjirannazu anime`,
        },
        {
            show_link: `/Library/Anime/TomodachiGame.html`,
            show_thumbnail: `/Library/Anime/img/16.jpg`,
            show_title: `>Tomodachi Game`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Tomodachi Game Tomodachi Gemu anime`,
        },
        {
            show_link: `/Library/Anime/KaguyaSama.html`,
            show_thumbnail: `/Library/Anime/img/17.jpg`,
            show_title: `Kaguya-Sama`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Kaguya-sama wa Kokurasetai Kaguya sama wa Kokurasetai Love is War anime`,
        },
        {
            show_link: `/Library/Anime/Kakegurui.html`,
            show_thumbnail: `/Library/Anime/img/18.jpg`,
            show_title: `Kakegurui`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Kakegure Kakegurui anime`,
        },
        {
            show_link: `/Library/Anime/ThatIRecentlyGotReincarnatedAsASlime.html`,
            show_thumbnail: `/Library/Anime/img/19.jpg`,
            show_title: `That I recently got Reincarnated as a Slime`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `That I recently got Reincarnated as a Slime Tensei Shitara Suraimu Datta Ken anime`,
        },
        {
            show_link: `/Library/Anime/RisingoftheShieldHero.html`,
            show_thumbnail: `/Library/Anime/img/20.jpg`,
            show_title: `Rising of the Shield hero`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Tate no Yūsha no Nariagari Rising of the Shield anime`,
        },
        {
            show_link: `/Library/Anime/VioletEvergarden.html`,
            show_thumbnail: `/Library/Anime/img/21.jpg`,
            show_title: `Violet Evergarden`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Vaioretto Evagaden Violet Evergarden anime`,
        },
        {
            show_link: `/Library/Anime/YourLieinApril.html`,
            show_thumbnail: `/Library/Anime/img/22.jpg`,
            show_title: `Your lie in April`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Shigatsu wa Kimi no Uso Your lie in April anime`,
        },
        {
            show_link: `/Library/Anime/KurokonoBasket.html`,
            show_thumbnail: `/Library/Anime/img/23.jpg`,
            show_title: `Kuroko no Basuke`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Kunoku no Basket Kuroko no Basuke anime`,
        },
        {
            show_link: `/Library/Anime/EnenNoShouboutai.html`,
            show_thumbnail: `/Library/Anime/img/24.jpg`,
            show_title: `Enen no Shouboutai`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Enen no Shouboutai Fireforce no Basuke anime`,
        },
        {
            show_link: `/Library/Anime/VinlandSaga.html`,
            show_thumbnail: `/Library/Anime/img/25.jpg`,
            show_title: `Vinland Saga`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Vinland Saga Vinrando Saga anime`,
        },
        {
            show_link: `/Library/Anime/TokyoRevengers.html`,
            show_thumbnail: `/Library/Anime/img/26.jpg`,
            show_title: `Tokyo Revengers`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Tokyo Revengers Tōkyō Ribenjāzu Tokyo Ribenjazu anime`,
        },
        {
            show_link: `/Library/Anime/MyHeroAcademia.html`,
            show_thumbnail: `/Library/Anime/img/27.jpg`,
            show_title: `My Hero Academia`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `My Hero Academia Boku no Hīrō Akademia Boku no Hiro Akademia anime`,
        },
        {
            show_link: `/Library/Anime/CowboyBebop.html`,
            show_thumbnail: `/Library/Anime/img/28.jpg`,
            show_title: `Cowboy Bebop`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Cowboy Bebop Kaubōi Bibappu Kauboi Bibappu anime`,
        },
        {
            show_link: `/Library/Anime/DeathNote.html`,
            show_thumbnail: `/Library/Anime/img/29.jpg`,
            show_title: `Death Note`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Death Note anime`,
        },
        {
            show_link: `/Library/Anime/OnePiece.html`,
            show_thumbnail: `/Library/Anime/img/30.jpg`,
            show_title: `One Piece`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `One Piece anime`,
        },
        {
            show_link: `/Library/Anime/OnePunchMan.html`,
            show_thumbnail: `/Library/Anime/img/31.jpg`,
            show_title: `One Punch man`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `One Punch man Wanpanman anime`,
        },
        {
            show_link: `/Library/Anime/HunterXHunter.html`,
            show_thumbnail: `/Library/Anime/img/32.jpg`,
            show_title: `Hunter X Hunter`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Hunter X Hunter anime`,
        },
        {
            show_link: `/Library/Anime/SteinsGate.html`,
            show_thumbnail: `/Library/Anime/img/33.jpg`,
            show_title: `Steins Gate`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Steins Gate anime`,
        },
        {
            show_link: `/Library/Anime/DragonBallZ.html`,
            show_thumbnail: `/Library/Anime/img/34.jpg`,
            show_title: `Dragon ball Z`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Dragon ball Z anime`,
        },
        {
            show_link: `/Library/Anime/Bleach.html`,
            show_thumbnail: `/Library/Anime/img/35.jpg`,
            show_title: `Bleach`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Bleach anime`,
        },
        {
            show_link: `/Library/Anime/AkameGaKill.html`,
            show_thumbnail: `/Library/Anime/img/36.jpg`,
            show_title: `Akame ga Kill!`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Akame ga Kill! Akame ga Kiru! anime`,
        },
        {
            show_link: `/Library/Anime/SwordArtOnline.html`,
            show_thumbnail: `/Library/Anime/img/37.jpg`,
            show_title: `Sword Art Online`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Sword Art Online Sōdo Āto Onrain Sodo Ato Onrain anime`,
        },
        {
            show_link: `/Library/Anime/BongouStrayDogs.html`,
            show_thumbnail: `/Library/Anime/img/38.jpg`,
            show_title: `Bongou Stray Dogs`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Bongou Stray Dogs Bungu Stray Dogs Bongu Stray Dogs Bungou Stray Dogs anime`,
        },
        {
            show_link: `/Library/Anime/MobPsycho.html`,
            show_thumbnail: `/Library/Anime/img/39.jpg`,
            show_title: `Mob Psycho`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Mob Psycho Mobu Saiko Hyaku anime`,
        },
        {
            show_link: `/Library/Anime/SamuraiChamploo.html`,
            show_thumbnail: `/Library/Anime/img/40.jpg`,
            show_title: `Samurai Champloo`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Samurai Champloo anime`,
        },
        {
            show_link: `/Library/Anime/HellSing.html`,
            show_thumbnail: `/Library/Anime/img/41.jpg`,
            show_title: `HellSing`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `HellSing Hell Sing anime`,
        },
        {
            show_link: `/Library/Anime/BlackLagoon.html`,
            show_thumbnail: `/Library/Anime/img/42.jpg`,
            show_title: `Black Lagoon`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Black Lagoon BlackLagoon anime`,
        },
        {
            show_link: `/Library/Anime/FutureDiary.html`,
            show_thumbnail: `/Library/Anime/img/43.jpg`,
            show_title: `Future Diary`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Future Diary anime`,
        },
        {
            show_link: `/Library/Anime/Another.html`,
            show_thumbnail: `/Library/Anime/img/44.jpg`,
            show_title: `Another`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Another anime`,
        },
        {
            show_link: `/Library/Anime/FairyTale.html`,
            show_thumbnail: `/Library/Anime/img/45.jpg`,
            show_title: `Fairy Tale`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Fairy Tale FairyTale anime`,
        },
        {
            show_link: `/Library/Anime/AfroSamurai.html`,
            show_thumbnail: `/Library/Anime/img/46.jpg`,
            show_title: `Afro Samurai`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Afro Samurai AfroSamurai anime`,
        },
        {
            show_link: `/Library/Anime/DemonKingDamaio.html`,
            show_thumbnail: `/Library/Anime/img/47.jpg`,
            show_title: `Demon King Damaio`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Demon King Damaio anime`,
        },
        {
            show_link: `/Library/Anime/ParadiseKiss.html`,
            show_thumbnail: `/Library/Anime/img/48.jpg`,
            show_title: `Paradise Kiss`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Paradise Kiss anime`,
        },
        {
            show_link: `/Library/Anime/Noragami.html`,
            show_thumbnail: `/Library/Anime/img/49.jpg`,
            show_title: `Noragami`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Noragami anime`,
        },
        {
            show_link: `/Library/Anime/GoblinSlayer.html`,
            show_thumbnail: `/Library/Anime/img/50.jpg`,
            show_title: `Goblin Slayer`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Goblin Slayer GoblinSlayer anime`,
        },
        {
            show_link: `/Library/Anime/DrStone.html`,
            show_thumbnail: `/Library/Anime/img/51.jpg`,
            show_title: `Dr Stone`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Dr Stone DrStone anime`,
        },
        {
            show_link: `/Library/Anime/BlueLock.html`,
            show_thumbnail: `/Library/Anime/img/52.jpg`,
            show_title: `BlueLock`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Blue Lock BlueLock anime`,
        },
        {
            show_link: `/Library/Anime/SeishunButa.html`,
            show_thumbnail: `/Library/Anime/img/53.jpg`,
            show_title: `Seishun Buta`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `SeishunButa Seishun Buta Yarō anime`,
        },
        {
            show_link: `/Library/Anime/DarkGathering.html`,
            show_thumbnail: `/Library/Anime/img/54.jpg`,
            show_title: `Dark Gathering`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Dark Gathering  Daku Gyazaringu Dāku Gyazaringu anime`,
        },
        {
            show_link: `/Library/Anime/TeruMomijiyama.html`,
            show_thumbnail: `/Library/Anime/img/55.jpg`,
            show_title: `Teru Momijiyama`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Shy Teru Momijiyama anime`,
        },
        {
            show_link: `/Library/Anime/MFGhost.html`,
            show_thumbnail: `/Library/Anime/img/56.jpg`,
            show_title: `MF Ghost`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `MF Ghost MFGhost MF Gōsuto MF Gosuto anime`,
        },
        {
            show_link: `/Library/Anime/YakusokuNoNeverland.html`,
            show_thumbnail: `/Library/Anime/img/57.jpg`,
            show_title: `Yakusoku no neverland`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Yakusoku no neverland Promised Neverland anime`,
        },
        {
            show_link: `/Library/Anime/SaikiK.html`,
            show_thumbnail: `/Library/Anime/img/58.jpg`,
            show_title: `Saiki K`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `SaikiK Saiki Kusuo no Sai-nan The Disastrous Life of Saiki K anime`,
        },
        {
            show_link: `/Library/Anime/HowARealisticHeroRebuiltTheKingdom.html`,
            show_thumbnail: `/Library/Anime/img/59.jpg`,
            show_title: `How A Realistic Hero RebuiltThe Kingdom`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `How A Realistic Hero RebuiltThe Kingdom Genjitsu Shugi Yusha no Okoku Saikenki Genjitsu Shugi Yūsha no Ōkoku Saikenki anime`,
        },
        {
            show_link: `/Library/Anime/AsteriskWar.html`,
            show_thumbnail: `/Library/Anime/img/60.jpg`,
            show_title: `Asterisk War`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `AsteriskWar Asterisk War Gakusen Toshi Asutarisuku anime`,
        },
        {
            show_link: `/Library/Anime/BlackCover.html`,
            show_thumbnail: `/Library/Anime/img/61.jpg`,
            show_title: `Black Cover`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `BlackCover Black Cover Burakku Kurōbā Burakku Kuroba anime`,
        },
        {
            show_link: `/Library/Anime/Bullbuster.html`,
            show_thumbnail: `/Library/Anime/img/62.jpg`,
            show_title: `Bullbuster`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Bullbuster Bull buster anime`,
        },
        {
            show_link: `/Library/Anime/ChainsawMan.html`,
            show_thumbnail: `/Library/Anime/img/63.jpg`,
            show_title: `Chainsaw man`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `ChainsawMan Chainsaw man Chensō Man Chenso Man anime`,
        },
        {
            show_link: `/Library/Anime/Dororo.html`,
            show_thumbnail: `/Library/Anime/img/64.jpg`,
            show_title: `Dororo`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Dororo anime`,
        },
        {
            show_link: `/Library/Anime/Erased.html`,
            show_thumbnail: `/Library/Anime/img/65.jpg`,
            show_title: `Erased`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Erased Boku dake ga Inai Mach anime`,
        },
        {
            show_link: `/Library/Anime/Vivy.html`,
            show_thumbnail: `/Library/Anime/img/66.jpg`,
            show_title: `Vivy`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Vivy Fluorite Eye's Song Vivy: Fluorite Eye's Song anime`,
        },
        {
            show_link: `/Library/Anime/AndYouThoughtThereIsNeverAGirlOnline.html`,
            show_thumbnail: `/Library/Anime/img/67.jpg`,
            show_title: `And You Thought There Is Never a Girl Online`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Netoge no Yome wa Onna no Ko Janai to Omotta And You Thought There Is Never a Girl Online anime`,
        },
        {
            show_link: `/Library/Anime/Haikyuu.html`,
            show_thumbnail: `/Library/Anime/img/68.jpg`,
            show_title: `Haikyuu`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Haikyū Haikyu Haikyuu anime`,
        },
        {
            show_link: `/Library/Anime/HowNotToSummonADemonLord.html`,
            show_thumbnail: `/Library/Anime/img/69.jpg`,
            show_title: `Go-Tobun no Hanayome`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Go-Tobun no Hanayome Go-Tōbun no Hanayome The Quintessential Quintuplets anime`,
        },
        {
            show_link: `/Library/Anime/HowNotToSummonADemonLord.html`,
            show_thumbnail: `/Library/Anime/img/70.jpg`,
            show_title: `How Not TO Summon a Demon Lord`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `HNTSADL Isekai Maō to Shōkan Shōjo no Dorei Majutsu Isekai Mao to Shokan Shojo no Dorei Majutsu How Not TO Summon a Demon Lord anime`,
        },
        {
            show_link: `/Library/Anime/Horimiya.html`,
            show_thumbnail: `/Library/Anime/img/71.jpg`,
            show_title: `Horimiya`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Hori-san to Miyamura-kun Hori and Miyamura Horimiya anime`,
        },
        {
            show_link: `/Library/Anime/KimitoBoku.html`,
            show_thumbnail: `/Library/Anime/img/72.jpg`,
            show_title: `Kimi to boku`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Kimi to boku anime`,
        },
        {
            show_link: `/Library/Anime/TomochanIsaGirl.html`,
            show_thumbnail: `/Library/Anime/img/73.jpg`,
            show_title: `Tomo-chan Is a Girl!`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Tomo-chan Is a Girl! Tomo-chan wa Onnanoko! anime`,
        },
        {
            show_link: `/Library/Anime/BochiTheRock.html`,
            show_thumbnail: `/Library/Anime/img/74.jpg`,
            show_title: `Bocabyhi the Rock`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Bocabyhi the Rock Hiroi Kikuri no Fukazake Nikki anime`,
        },
        {
            show_link: `/Library/Anime/LinkClick.html`,
            show_thumbnail: `/Library/Anime/img/75.jpg`,
            show_title: `Link Click`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Link Click Shíguāng Dàilǐrén Shiguang Dailiren anime`,
        },
        {
            show_link: `/Library/Anime/MyLifeasInuSansDog.html`,
            show_thumbnail: `/Library/Anime/img/76.jpg`,
            show_title: `My Life as Inu-san's dog`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `My Life as Inu-san's dog Inu ni Nattara Suki na Hito ni Hirowareta anime`,
        },
        {
            show_link: `/Library/Anime/MyStepmomsDaughterisMyEx.html`,
            show_thumbnail: `/Library/Anime/img/77.jpg`,
            show_title: `My Stepmom's daughter is my Ex`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `My Stepmom's daughter is my Ex Irido Mizuto anime`,
        },
        {
            show_link: `/Library/Anime/Overlord.html`,
            show_thumbnail: `/Library/Anime/img/78.jpg`,
            show_title: `Overlord`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Ōbārōdo Obarodo Overlord anime`,
        },
        {
            show_link: `/Library/Anime/TalentlessNana.html`,
            show_thumbnail: `/Library/Anime/img/79.jpg`,
            show_title: `Talentless Nana`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `TalentlessNana Talentless Nana Munō na Nana Muno na Nana anime`,
        },
        {
            show_link: `/Library/Anime/VanitasNoCarte.html`,
            show_thumbnail: `/Library/Anime/img/80.jpg`,
            show_title: `Vanitas no Carte`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Vanitasu no Karute Vanitas no Carte anime anime`,
        },
        {
            show_link: `/Library/Anime/InitialD.html`,
            show_thumbnail: `/Library/Anime/img/81.jpg`,
            show_title: `Initial D`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `InitialD Initial D Inisharu Dī Inisharu Di anime`,
        },
        {
            show_link: `/Library/Anime/AssassinationClassroom.html`,
            show_thumbnail: `/Library/Anime/img/82.jpg`,
            show_title: `Assassination Classroom`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Assassination Classroom Ansatsu Kyōshitsu Ansatsu Kyoshitsu anime`,
        },
        {
            show_link: `/Library/Anime/MashleMagicAndMuscle.html`,
            show_thumbnail: `/Library/Anime/img/83.jpg`,
            show_title: `Mashle Magic and Muscle`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Mashle Magic and Muscle Masshuru anime`,
        },
        {
            show_link: `/Library/Anime/TrainToTheEndOfTheWorld.html`,
            show_thumbnail: `/Library/Anime/img/84.jpg`,
            show_title: `Train to the End of the world`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Train to the End of the world anime`,
        },
        {
            show_link: `/Library/Anime/Yatagarasu.html`,
            show_thumbnail: `/Library/Anime/img/85.jpg`,
            show_title: `Yatagarasu`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Yatagarasu anime`,
        },
        {
            show_link: `/Library/Anime/WindBreaker.html`,
            show_thumbnail: `/Library/Anime/img/86.jpg`,
            show_title: `Wind Breaker`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Wind Breaker Uindo Bureikā Uindo Bureika anime`,
        },
        {
            show_link: `/Library/Anime/ApothecaryDiaries.html`,
            show_thumbnail: `/Library/Anime/img/87.jpg`,
            show_title: `Apothecary Diaries`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Apothecary Diaries Kusuriya no Hitorigoto anime`,
        },
        {
            show_link: `/Library/Anime/ASignOfAffection.html`,
            show_thumbnail: `/Library/Anime/img/88.jpg`,
            show_title: `A Sign Of Affection`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `A Sign Of Affection Hibike! Yūfoniamu Hibike! Yufoniamu anime`,
        },
        {
            show_link: `/Library/Anime/SoundEuphonium.html`,
            show_thumbnail: `/Library/Anime/img/89.jpg`,
            show_title: `Sound! Euphonium`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Sound! Euphonium anime`,
        },
        {
            show_link: `/Library/Anime/TheWitchAndTheBeast.html`,
            show_thumbnail: `/Library/Anime/img/90.jpg`,
            show_title: `The Witch And The Beast`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `The Witch And The Beast anime`,
        },
        {
            show_link: `/Library/Anime/Black Butler.html`,
            show_thumbnail: `/Library/Anime/img/91.jpg`,
            show_title: `Black Butler`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Black Butler Kuroshitsuji anime`,
        },
        {
            show_link: `/Library/Anime/HighSpeedEtoile.html`,
            show_thumbnail: `/Library/Anime/img/92.jpg`,
            show_title: `HighSpeed Etoile`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `High Speed Etoile HighSpeed Etoile HIGHSPEED Étoile anime`,
        },
        {
            show_link: `/Library/Anime/MetallicRouge.html`,
            show_thumbnail: `/Library/Anime/img/93.jpg`,
            show_title: `Metallic Rouge`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Metallic Rouge Metarikku Rūju Metarikku Ruju anime`,
        },
        {
            show_link: `/Library/Anime/AkumaDrive.html`,
            show_thumbnail: `/Library/Anime/img/94.jpg`,
            show_title: `Akuma Drive`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Akuma Drive AkumaDrive anime`,
        },
        {
            show_link: `/Library/Anime/AstroNote.html`,
            show_thumbnail: `/Library/Anime/img/95.jpg`,
            show_title: `Astro Note`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Astro Note Asutoro Nōto Asutoro Noto anime`,
        },
        {
            show_link: `/Library/Anime/HeavenOfficialsBlessing.html`,
            show_thumbnail: `/Library/Anime/img/96.jpg`,
            show_title: `Heaven Official's Blessing`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Heaven Officials Blessings Heaven Official's Blessings Tiān Guān Cì Fú Tian Guan Ci Fu anime`,
        },
        {
            show_link: `/Library/Anime/TheWrongWayToUseHealingMagic.html`,
            show_thumbnail: `/Library/Anime/img/97.jpg`,
            show_title: `The Wrong Way To Use Healing Magic`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `The Wrong Way To Use Healing Magic anime`,
        },
        {
            show_link: `/Library/Anime/Konosuba.html`,
            show_thumbnail: `/Library/Anime/img/98.jpg`,
            show_title: `Konosuba`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Konosuba God's Blessing on This Wonderful World! KonoSuba: God's Blessing on This Wonderful World! anime`,
        },
        {
            show_link: `/Library/Anime/KaijuNo8.html`,
            show_thumbnail: `/Library/Anime/img/99.jpg`,
            show_title: `Kaiju No. 8`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Kaiju No. 8 Kaiju No.8 Kaiju No8 KaijuNo8 Kaijū Hachigō Kaiju Hachigo anime`,
        },
        {
            show_link: `/Library/Anime/TheNewGate.html`,
            show_thumbnail: `/Library/Anime/img/100.jpg`,
            show_title: `The New Gate`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `The New Gate anime`,
        },
        {
            show_link: `/Library/Anime/SoloLeveling.html`,
            show_thumbnail: `/Library/Anime/img/101.jpg`,
            show_title: `Solo Leveling`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `SoloLeveling Solo Leveling Na Honjaman Rebeleop anime`,
        },
        {
            show_link: `/Library/Anime/DailyLifeOfAnImmortalKing.html`,
            show_thumbnail: `/Library/Anime/img/102.jpg`,
            show_title: `Daily Life Of An Immortal King`,
            show_type: `Anime`,
            show_status: ``,
            show_languages: ``,
            show_subtitles: ``,
            show_genre: ``,
            show_theme: ``,
            show_year: ``,
            show_aired: ``,
            show_studios: ``,
            show_country: ``,
            show_foreground: ``,
            show_background: ``,
            show_quality: ``,
            show_rating: ``,
            show_scores: ``,
            show_trailers: [{show_trl: null}],
            show_movies: [{show_mov: null}],
            show_episodes: [{show_ep: null,}],
            show_description: ``,
            show_searchKey: `Daily Life Of An Immortal King Xiān Wáng de Rìcháng Shēnghuó Xian Wáng de Richang Shenghuo anime`,
        },
    ];




